### ISSUE TITLE
Need to put the ids of the created or existing aws security groups to be used in confing

### ISSUE THREAD

**Issue by wonderslug** [cloudera-labs/cloudera.exe#31]
Something along the lines of the following variables.

```
infra:
  aws:
    vpc:
      existing:
        security_groups:
          default_id:
          knox_id:
```
